import Head from 'next/head';
import Footer from '../components/footer/footer';

export default function AdminPage() {
  return (
    <div>
        <Head>
            <title>Admin Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="h-full">
                <div className="w-full bg-black" >
                    <div className="container:md flex flex-col flex-wrap items-center space-y-1 py-4 mx-auto  md:flex-row md:max-w-xl">
                        <div className="  text-white items-start">
                            <h1 className="text-xl">Admin</h1>
                        </div>
                        <div className=" text-white items-center mx-auto">
                            <span> Home </span>
                            <span> Home </span>
                            <span> Home </span>
                            <span> Home </span>
                        </div>
                        <div className="text-white items-end">
                            <div className="">
                                <button type="button" className="bg-red-700 px-2 py-1">Log Out</button>
                                
                            </div>
                        </div>
                    </div>    
                </div>

                <div className="container:md flex flex-col  items-center">
                    <div className="flex flex-col h-full bg-white ">
                        
                            <div className="flex flex-col border-2 border-white  py-11 px-11 md:flex-row md:space-x-4"> 
                                <div className="flex flex-col border-2 border-white bg-gray-300 my-8">
                                    <div className="text-xl text-center py-4 px-4">
                                        <h1 className="pb-4">Criar produto:</h1>
                                            <div className="border-2 border-gray-300 px-4 py-4 mb-4">
                                                <div className="flex flex-col text-lg text-left mb-8">
                                                    <label>title:</label>
                                                    <input className="bg-white w-auto m-1"></input>
                                                    <label>price:</label>
                                                    <input className="bg-white w-auto m-1"></input>
                                                    <label>color:</label>
                                                    <input className="bg-white w-auto m-1"></input>
                                                    <label>tags:</label>
                                                    <input className="bg-white w-auto m-1"></input>
                                                </div>
                                                <div className="flex flex-row  bg-gray-300 space-x-3" >
                                                    <button type="button" onClick={() => console.log("Produto adicionado!")} className="text-md bg-green-500 w-1/3 py-4">Add</button>
                                                    <button type="button" onClick={() => console.log("Produto removido!")} className="text-md bg-red-500 w-1/3 py-4">Delete</button>
                                                    <button type="button" onClick={() => console.log("Produto atualizado!")} className="text-md bg-yellow-500 w-1/3 py-4">Edit</button>
                                                </div>
                                            </div>
                                    </div>
                                </div>   
                            </div>   
                    </div>

                    
                </div>
                
        </section>
        <footer>
          <Footer></Footer>
        </footer>


    </div>
  )
}