import Head from 'next/head';
import Footer from '../components/footer/footer';
import { createProduct } from '../utils/api/product';

export default function AdminPage() {
  return (
    <div>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-full">
        <div className="w-full bg-black">
          <div className="container:md flex flex-col flex-wrap items-center space-y-1 py-4 mx-auto  md:flex-row md:max-w-xl">
            <div className="  text-white items-start">
              <h1 className="text-xl">Admin</h1>
            </div>
            <div className=" text-white items-center mx-auto">
              <span></span>
              <span></span>
              <span></span>
              <span></span>
            </div>
            <hr className=""></hr>
            <div className="text-white items-end">
              <div className="">
                <button type="button" className="bg-red-700 px-2 py-1">
                  Log Out
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="container:xl flex flex-col justify-center items-center md:flex-row md:space-x-4">
          <div className="flex flex-col  bg-white ">
            <div className="flex flex-col border-2 border-white  py-11 px-11 ">
              <div className="flex flex-col border-2 border-white bg-gray-300 my-8">
                <div className="text-xl text-center py-4 px-4">
                  <h1 className="pb-4">Create product:</h1>
                  <div className="border-2 border-gray-300 px-4 py-4 mb-4">
                    <div className="flex flex-col text-lg text-left mb-8">
                      <label>Title:</label>
                      <input
                        id="title"
                        type="text"
                        className="bg-white w-auto m-1"
                      ></input>
                      <label>Price:</label>
                      <input
                        id="price"
                        type="text"
                        className="bg-white w-auto m-1"
                      ></input>
                      <label>Color:</label>
                      <input
                        id="color"
                        type="text"
                        className="bg-white w-auto m-1"
                      ></input>
                      <label>Tags:</label>
                      <input
                        id="tags"
                        type="text"
                        className="bg-white w-auto m-1"
                      ></input>
                    </div>
                    <div className="flex flex-row  bg-gray-300">
                      <button
                        type="button"
                        onClick={() => createProduct()}
                        className="text-md w-full bg-green-500 py-4"
                      >
                        Add
                      </button>
                    </div>
                  </div>
                </div>
            
            </div>
            </div>
          </div>

          <div className="flex flex-col h-96   bg-gray-300 ">
                    
                    <div className="">
                        <h1 className="text-xl py-4 px-24">Inventory</h1>
                        <ul className="px-4 mb-4">
                            <li>Product:</li>
                            <li>Product:</li>
                            <li>Product:</li>
                            <li>Product:</li>
                            <li>Product:</li>
                            <li>Product:</li>

                        </ul>
                        <div className="flex flex-row px-4">
                                <button type="button"
                                    onClick={() => createProduct()} className="text-md w-full bg-red-500 py-4">
                                    Delete</button>
                                <button type="button"
                                onClick={() => createProduct()} className="text-md w-full bg-yellow-500 py-4">
                                Edit</button>
                        </div>
                    </div>

            </div>
        </div>
        
      </section>
      <footer>
        <Footer></Footer>
      </footer>
    </div>
  );
}
