import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/navbar/navbar';
import Footer from '../components/footer/footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Nav></Nav>
      </nav>

      <div class="container max-w-7xl mx-auto p-8">
        <div class="flex flex-row flex-wrap -mx-2">
          <div class="w-full md:w-1/2 h-64 md:h-auto mb-4 px-2">
            <a
              class="block w-full h-full bg-grey-dark bg-no-repeat bg-center bg-cover"
              href="#"
              title="Link"
            >
              Link
            </a>
          </div>
          <div class="w-full md:w-1/2 mb-4 px-2">
            <div class="flex flex-col sm:flex-row md:flex-col -mx-2">
              <div class="w-full sm:w-1/2 md:w-full h-48 xl:h-64 mb-4 sm:mb-0 md:mb-4 px-2">
                <a
                  class="block w-full h-full bg-grey-dark bg-no-repeat bg-center bg-cover"
                  href="#"
                  title="Link"
                >
                  Link
                </a>
              </div>
              <div class="w-full sm:w-1/2 md:w-full h-48 xl:h-64 px-2">
                <a
                  class="block w-full h-full bg-grey-dark bg-no-repeat bg-center bg-cover"
                  href="#"
                  title="Link"
                >
                  Link
                </a>
              </div>
            </div>
          </div>
          <div class="w-full sm:w-1/3 h-32 md:h-48 mb-4 sm:mb-0 px-2">
            <a
              class="block w-full h-full bg-grey-dark bg-no-repeat bg-center bg-cover"
              href="#"
              title="Link"
            >
              Link
            </a>
          </div>
          <div class="w-full sm:w-1/3 h-32 md:h-48 mb-4 sm:mb-0 px-2">
            <a
              class="block w-full h-full bg-grey-dark bg-no-repeat bg-center bg-cover"
              href="#"
              title="Link"
            >
              Link
            </a>
          </div>
          <div class="w-full sm:w-1/3 h-32 md:h-48 px-2">
            <a
              class="block w-full h-full bg-grey-dark bg-no-repeat bg-center bg-cover"
              href="#"
              title="Link"
            >
              Link
            </a>
          </div>
        </div>
      </div>
      <footer>
        <Footer></Footer>
      </footer>
    </div>
  );
}
