import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/navbar/navbar';
import Footer from '../components/footer/footer';



export default function TestPage() {
  return (
    <div>
      <Head>
        <title>Pierce Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section class="h-screen w-full px-8 text-gray-700 bg-white">
        <Nav></Nav>
         
        <hr class="border-gray-600" />
        <div className="container flex flex-col flex-wrap items-center justify-between py-5 mx-auto md:flex-row max-w-7xl">
          <div className="row-auto flex bg-black">
            <div>
              <h1 className="text-xl bg-white">TEST PAGE</h1>
            </div>
            <div>
              <h1 className="text-xl bg-white">TEST PAGE</h1>
            </div>
            <div>
              <h1 className="text-xl bg-white">TEST PAGE</h1>
            </div>
          </div>
        </div>
      </section>

      <footer>
        <Footer></Footer>
      </footer>
    </div>
  );
}
