import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/navbar/navbar';
import Footer from '../components/footer/footer';
import Link from 'next/Link';


export default function TestPage() {
  return (
 
    <div>
      <Head>
        <title>Pierce Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Nav></ Nav>
      </nav>
    
       <main className="relative h-screen w-screen">
           <div className="row-auto flex bg-black">
                <div>
                    <h1 className="text-xl bg-white">
                        TEST PAGE
                    </h1>
                </div>
                <div>
                    <h1 className="text-xl bg-white">
                        TEST PAGE
                    </h1>
                </div>
                <div>
                    <h1 className="text-xl bg-white">
                        TEST PAGE
                    </h1>
                </div>
           </div>
       </main> 


      <footer>
         <Footer></Footer>
      </footer>
    </div>
  )
}
